// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI72MaQBd5K6vB2yFFRX1eCxCk2Z5qqOw',
    appId: '1:1048900494296:web:c2e2b639a8fb4a0a9cc8ad',
    messagingSenderId: '1048900494296',
    projectId: 'chat-app-dcff2',
    authDomain: 'chat-app-dcff2.firebaseapp.com',
    storageBucket: 'chat-app-dcff2.appspot.com',
    measurementId: 'G-G6KCBTRE36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBItx9T_I0k3aoUGUTJlmuYhQUsQEPwh4w',
    appId: '1:1048900494296:android:f3cab24a46b520be9cc8ad',
    messagingSenderId: '1048900494296',
    projectId: 'chat-app-dcff2',
    storageBucket: 'chat-app-dcff2.appspot.com',
  );
}
